spring:
  application:
    name: gateway
  profiles:
    active: thoslide  #develop thoslide
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 15MB
  mvc:
    favicon:
      enabled: false

#logging:
#  backup: /opt/pathology/backup/
#  path: /opt/pathology/logs/gateway
#
#zuul:
#  ignoredServices: '*'
#  host:
#    connect-timeout-millis: 50000
#    socket-timeout-millis: 50000
#
#  routes:
#    path-service:
#        path: /path/**
#        url: http://localhost:8082
#        stripPrefix: false
#        sensitiveHeaders:
#    insights-service:
#        path: /insights/**
#        url: http://localhost:8083
#        stripPrefix: false
#        sensitiveHeaders:
#    web-service:
#        path: /web/**
#        url: http://192.168.68.191:9090
#        stripPrefix: true
#        sensitiveHeaders:



