spring:
  application:
    name: gateway
  profiles:
    active: 100  #develop thoslide
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 15MB
  mvc:
    favicon:
      enabled: false
server:
  port: 8083
  tomcat:
    uriEncoding: UTF-8
    compression:
        enabled: true
    maxHttpPostSize: 8388608
    mime-types: text/html,text/css,application/json,application/javascript

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 200000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

#logging:
#  backup: /opt/pathology/backup/
#  path: /opt/pathology/logs/gateway
#
#zuul:
#  ignoredServices: '*'
#  host:
#    connect-timeout-millis: 50000
#    socket-timeout-millis: 50000
#
#  routes:
#    path-service:
#        path: /path/**
#        url: http://localhost:8082
#        stripPrefix: false
#        sensitiveHeaders:
#    insights-service:
#        path: /insights/**
#        url: http://localhost:8083
#        stripPrefix: false
#        sensitiveHeaders:
#    web-service:
#        path: /web/**
#        url: http://192.168.68.191:9090
#        stripPrefix: true
#        sensitiveHeaders:



